Update CSS token per new design system theming capability
AlaskaAirlines/auro-datetime pull request #34
Opened 2023-11-08 09:46 UTC by fajar-apri-alaska

# Alaska Airlines Pull Request

**Fixes:** #33 

## Summary:

- Update the package dependency only, since there's no styling applied to this component.

## Type of change:

Please delete options that are not relevant.

- [x] Revision of an existing capability

## Checklist:

- [x] My update follows the CONTRIBUTING guidelines of this project
- [x] I have performed a self-review of my own update

**By submitting this Pull Request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your submission._

**Thank you for your submission!**<br>
-- Auro Design System Team

2023-11-10 03:48 UTC, blackfalcon requested changes
Please update all npm dependencies and update the repo to support Node 18 || 20 per the Node support policy 

https://auro.alaskaair.com/node-support

2023-11-10 03:48 UTC, blackfalcon commented on package.json
>      "@alaskaairux/design-tokens": "^3.14.0",
Remove from the repo

2023-11-10 03:48 UTC, blackfalcon commented on src/style.scss
> +@import './../node_modules/@aurodesignsystem/design-tokens/dist/tokens/SassCustomProperties';
```suggestion
```

this reference is not needed.

2023-11-10 11:00 UTC, fajar-apri-alaska commented
I have pushed a new commit per above feedback.

2023-11-16 12:23 UTC, jason-capsule42 approved these changes

2023-11-16 12:23 UTC, merged

2023-11-16 12:25 UTC, blackfalcon commented
:tada: This PR is included in version 2.0.1 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@aurodesignsystem/auro-datetime/v/2.0.1)
- [GitHub release](https://github.com/AlaskaAirlines/auro-datetime/releases/tag/v2.0.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: